refactor: Change chart repo to new repo

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -53,22 +53,48 @@ jobs:
         run: |
           aws eks update-kubeconfig --name test --region ap-southeast-1
       
-      - name: Manual Approval
-        id: manual-approval
-        if: github.event_name == 'workflow_dispatch'
-        uses: technote-space/workflow-dispatch-action@v1
-        with:
-          approve-comment: "Approve deployment"
-          cancel-comment: "Cancel deployment"
-    
-      - name: Add chart and update
-        if: github.event_name == 'workflow_dispatch' && steps.manual-approval.outputs.approved == 'true'
+      - name: Manual approval
+        id: select-options
         run: |
-          helm repo add tomcat-chart https://dinushchathurya.github.io/tomcat-helm-multi-env --force-update
-          helm repo update
-          helm repo list
-          helm upgrade tomcat-chart tomcat-chart/tomcat-chart --install --devel \
-            --version ${{ steps.random-version.outputs.version }} \
-            --namespace dev --debug
+          echo "##[group]Select an option"
+          echo "::set-output name=selectedOption::$( \
+            bash -c ' \
+              options=("Option A" "Option B" "Option C"); \
+              select opt in "${options[@]}"; do \
+                case $opt in \
+                  "OK") echo "ok"; break;; \
+                  "CANCEL") echo "cancel"; break;; \
+                  *) echo "Invalid option";; \
+                esac; \
+              done \
+            ' \
+          )"
+          echo "##[endgroup]"
+            
+      - name: Add chart and update repo
+        run: |
+          selectedOption=${{ steps.select-options.outputs.selectedOption }}
+          case $selectedOption in
+            "ok")
+              # Run specific steps for Option A
+              helm repo add tomcat-chart https://dinushchathurya.github.io/tomcat-helm-multi-env --force-update
+              helm repo update
+              helm repo list
+              helm upgrade tomcat-chart tomcat-chart/tomcat-chart --install --devel \
+                --version ${{ steps.random-version.outputs.version }} \
+                --namespace dev --debug
+              # ...
+              ;;
+            "cancel")
+              # Run specific steps for Option B
+              exit 1
+              # ...
+              ;;
+            *)
+              echo "Invalid option selected. Exiting workflow."
+              exit 1
+              ;;
+          esac
+          
 
 
